### ISSUE TITLE
Review chapters 3 and 4

### ISSUE THREAD

**Issue by kamuda1** [kamuda1/dissertation#5]
Requesting a review of chapters 3 and 4. A few sections in chapter still 4 need to be finalized. I'll upload a new version with both chapters complete soon.

[KamudaDissertationDraft.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3493551/KamudaDissertationDraft.pdf)

**Comment by kamuda1** [comment]
Updates

[KamudaDissertationDraft_updated.pdf.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3499564/KamudaDissertationDraft_updated.pdf.pdf)

**Comment by katyhuff** [comment]
I'll look at this ASAP. That said... Here are some hopefully constructive pro-tips for a future data scientist... :
- I know you slacked it to me. But -- if you want someone to see a github issue, your best bet is to at least @-mention them.
- In the case that you own the repo and you're assigning a task, add the assignee as an Actual assignee on the issue (because I, for example, have a browser bookmark to https://github.com/issues/assigned which I do look at... and this issue isn't on it because I wasn't assigned.)

**Comment by kamuda1** [comment]
You will need to accept the [collaboration request](https://github.com/kamuda1/kamuda-2019-dissertation/invitations) for me to @-mention you and assign you to issues. I forgot to mention this in the slack message.

**Comment by katyhuff** [comment]
you can always @-mention.

**Comment by kamuda1** [comment]
@katyhuff Final draft updates to both chapters. I also added results content to chapter 5, will have the discussion section for that done soon.

[Kamuda_Dissertation_updated.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3570240/Kamuda_Dissertation_updated.pdf)

**Comment by katyhuff** [comment]
closed as duplicate
